### ISSUE TITLE
Erreur: Index nom définis

### ISSUE THREAD

**Issue by Bullot78** [pluginsGLPI/purgelogs#10]
Bonjour,
avec GLPI en 0.90.1 et purgelogs en 0.85+1.2, en mode debug, sur la page de configuration, pour chacun des objets j'ai un PHP Notice m'indiquant une variable non définie dans le fichier :
purgelogs/inc/config.class.php.
Javais le même problème avec le plugin 0.85+1.1.
j'ai récupéré la dernière version du fichier config.class.php depuis git mais j'ai toujours le problème.

indexes non-définis:
purge_addrelation
purge_createitem
purge_restoreitem
purge_comments
purge_deleterelation
purge_deleteitem
purge_updateitem
purge_datemod
purge_computer_software_install
purge_software_version_install
...

bref, tous on la même erreur.

Merci de votre retour.

**Comment by trasher** [comment]
Il semblerait que la configuration n'ait pas été récupérée correctement en base.

Il faudrait vérifier les logs de glpi (erreurs php et sql) lors de l'affichage de cette page pour en savoir un peu plus.
