### ISSUE TITLE
Differentiate empty log to log cleared

### ISSUE THREAD

**Issue by sulian** [pluginsGLPI/purgelogs#12]
Following our discussion with @trasher and @orthagh, can you add the possibility for the plugin to add an entry when the log is cleared ? 

the goal is to differentiate empty log to log cleared.

Thanks

**Comment by sulian** [comment]
My english is so bad...

**Comment by trasher** [comment]
see glpi-project/glpi#1218 for reference

**Comment by trasher** [comment]
Done in proposed PR on GLPI core
