### ISSUE TITLE
Purge IPNetwork Itemtype

### ISSUE THREAD

**Issue by Kahalisto** [pluginsGLPI/purgelogs#2]
Hello !

FusionInventory generates a huge quantity of  log  called IPNetwork in the itemtype field when i use Network Inventory.

Could you please add this purge in your plugin ?

Thank you !

**Comment by wawax** [comment]
Hi Kahalisto,

Could you give us more details about the issue ? 
What are theses logs about ? Can you copy/paste an example as it is stored in glpi_logs ?

Thanks in advance,

**Comment by Kahalisto** [comment]
Hi wawax
Thanks your fast answered

These logs are used in this part of GLPI :
Setup > Dropdowns > Ip Networks

This is an example for a single Ip network 
![capture](https://cloud.githubusercontent.com/assets/14975836/10278584/ad24e394-6b5e-11e5-8e59-789cadcad6ae.JPG)

In glpi_logs it look like that 
![capture](https://cloud.githubusercontent.com/assets/14975836/10278642/163ba6a6-6b5f-11e5-9eb3-5b7a9451e2e5.JPG)

**Comment by blerohellec** [comment]
This type of logs is purged by option General / Add relation between items
