### ISSUE TITLE
Add size informations

### ISSUE THREAD

**Issue by nqb** [pluginsGLPI/purgelogs#21]
Hello,

It will be nice to have size informations for each section (General, Software, etc.) with a sum for all sections.
Two size informations should appeared :
- currently size of logs (before purge)
- future size of logs (after purge)

Units for size : SI standard (kB, MB, GB, TB).

With this feature, you have an idea about size of your logs (before and after purge). On top of that, you can identify tables with unexpected size.

**Comment by nqb** [comment]
See glpi-project/glpi/pull/3845

**Comment by trasher** [comment]
I forget to add comment I've prepared...

To make things clear, I'm not going to work on this; I do not even know how to achieve that. Please open a request on [GLPI suggestion website](http://suggest.glpi-project.org).

**Comment by nqb** [comment]
Done https://glpi.userecho.com/communities/1/topics/829-add-size-informations-on-purgelogs-form
