### ISSUE TITLE
OCS not getting deleted

### ISSUE THREAD

**Issue by Eon9D** [pluginsGLPI/purgelogs#22]
GLPI 9.2.2
Purge history 1.3.0

I've set the section Software and OCSNG in purge logs to "delete all" and executed cron.
I still have plenty of these records in the database:

`

id | itemtype | items_id | itemtype_link | linked_action | user_name | date_mod | id_search_option | old_value | new_value
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
2741 | Computer | 122 | PluginOcsinventoryngOcslink | 1010 | cron_ocsng | 10.05.2017 13:44 | 0 | XXXX | XXXX
220079 | Computer | 77 | Computer_SoftwareVersion#date_install | 21 | ocsinventoryng | 20.05.2017 05:00 | 0 | XXXX | XXXX

`

Can you fix this ?
Thanks

**Comment by trasher** [comment]
`linked_action` with `21` value means a relation update that is indeed not managed. I've proposed to add it on the existing "Add relation" parameter.
As of the OCS entry, I do not know what it is; and OCS purge config is quite "complex". See https://github.com/glpi-project/glpi/issues/1218 and the associated pull request.
