### ISSUE TITLE
L'installation pour 0.90 ne fonctionne pas

### ISSUE THREAD

**Issue by cdlabal** [pluginsGLPI/purgelogs#3]
Bonjour,
Après décompression de l'archive du plugin dans glpi/plugin et affectation du user apache (www-data) sur l'arborescence, le plugin n'est pas visible dans GLPI 0.90.

**Comment by btry** [comment]
Bonjour,
Si le plugin n'apparait pas, c'est probablement lié à un problème de permissions. 

Comme vous avez changé le propriétaire des fichiers, vérifiez que les droits d'accès sont au moins à 700 ou 770.

Vérifiez également le propriétaire et les permissions du dossier purgelogs lui-même.

**Comment by cdlabal** [comment]
Merci pour cette réponse rapide.

Le problème venait en fait du nom du dossier. La décompression du Tar créée par défaut le dossier /purgelogs-0.85-1.1. Je l’ai renommé en /purgelogs et GLPI voit bien le plugin à présent.

 

Merci

 

 

Philippe Chauvin

Responsable Production Informatique

Tel:  +33 (0)1 49 62 28 62

Mob: +33 (0)6 30 98 70 44  

Fax: +33 (0)1 45 76 68 40

E-mail: philippe.chauvin@jtekt-eu.com <mailto:philippe.chauvin@jtekt-eu.com> 

 

JTEKT-HPI  

26 rue condorcet - ZI

94432 Chennevières sur marne

Web: http://www.jtekt-hpi.com <http://www.jtekt-hpi.com> 

 

De : btry [mailto:notifications@github.com] 
Envoyé : mardi 13 octobre 2015 15:21
À : pluginsGLPI/purgelogs
Cc : CHAUVIN Philippe
Objet : Re: [purgelogs] L'installation pour 0.90 ne fonctionne pas (#3)

 

Bonjour,
Si le plugin n'apparait pas, c'est probablement lié à un problème de permissions. 

Comme vous avez changé le propriétaire des fichiers, vérifiez que les droits d'accès sont au moins à 700 ou 770.

Vérifiez également le propriétaire et les permissions du dossier purgelogs lui-même.

—
Reply to this email directly or view it on GitHub <https://github.com/pluginsGLPI/purgelogs/issues/3#issuecomment-147711897> . 


========================================================================
Ce message et toutes les pieces jointes sont propriete de JTEKT EUROPE et susceptibles de contenir des informations
confidentielles a l'intention exclusive de ses destinataires. Si vous avez recu ce message par erreur veuillez contacter l'emetteur
et effacer ce message et ses pieces jointes de votre systeme. Si celui ci vous est parvenu incomplet ou altere, merci d'en avertir
l'expediteur par retour. Toute utilisation, diffusion ou copie non expressement autorisee par JTEKT EUROPE par ecrit est strictement interdite. 
------------------------------------------------------------------------------------------------------------ 
This message and any attachments are JTEKT EUROPE property and may contain confidential information intended
solely for the addressees. If your are not the intended recipient of this message, please contact the sender and delete this message
and any attachment from your system. If you have received it uncomplete or altered, please notify the author by replying to his
e-mail immediately. Any unauthorized use, disclosure or copy not expressly authorized by JTEKT EUROPE in writing is strictly prohibited. 
========================================================================
Copyright JTEKT EUROPE 2006
