### ISSUE TITLE
Plugin Purgelogs Installation issue

### ISSUE THREAD

**Issue by scoda974** [pluginsGLPI/purgelogs#5]
Hi,
I tried to install Purgelogs as a standard plugin  : I untared the .tar file in the plugins directory of GLPI and gave the rights I need.
Then, when I go back to GLPi interface >configuration>plugins, I can't see the line and the option to install the plugin, as the directory I untared was not there...
Is there another way ton install the plugin?

My GLPI version is 0.90.3

Thanks,

**Comment by potomuss** [comment]
I experience this issue as well. Same procedure as above. GLPI 90.3.
Help!

**Comment by btry** [comment]
Hi

Can you show the path of the extracted setup.php ?

**Comment by potomuss** [comment]
My path is:
/var/www/glpi/plugins/purgelogs-0.85-1.1/setup.php

**Comment by potomuss** [comment]
Sorry, I posted on github but probably should have replied here.
Path is /var/www/glpi/plugins/purgelogs-0.85-1.1

**Comment by btry** [comment]
Rename ```purgelogs-0.85-1.1``` into ```purgelogs``` and your plugin should be available in GLPi.

**Comment by potomuss** [comment]
That did the trick. I think I tried that earlier but didn't logout and back
in. (First time using a plugin)
Thank you!!!

**Comment by scoda974** [comment]
It worked!!! Thank you!
