### ISSUE TITLE
Add remove strings of the FusionInventory plugin in the log

### ISSUE THREAD

**Issue by AircraftRu** [pluginsGLPI/purgelogs#6]
Hello,
Please, Add remove strings of the FusionInventory plugin in the logs. This is big problem. He writes a lot of string in log.  I wrote script of bash of Linux that remove strings of the FusionInventory plugin.

And add Russian language in this plugin. I translated him on Transifex.

**Comment by lolokai** [comment]
Any news from this feature ?

**Comment by AircraftRu** [comment]
Need such script like: `DELETE FROM `glpi_logs` WHERE `user_name` LIKE '%Plugin_FusionInventory%' AND `date_mod` <= DATE_ADD(NOW(), INTERVAL -6 MONTH);`
-6 MONTH - it's my option.

**Comment by trasher** [comment]
Will be done in GLPI core as of 9.3; see #11 and glpi-project/glpi#1218
