### ISSUE TITLE
PHP Fatal Error during upgrade

### ISSUE THREAD

**Issue by pvasener** [pluginsGLPI/purgelogs#9]
I upgraded a test site from GLPI 0.90.5 to 9.1 and so I tried to upgrade this plug-in from version 0.85+1.1 to 0.85+1.2 marked as compatible with GLPI 9.1 but when I hit the plug-in 'Upgrade' button, I get a blank page with the following PHP Fatal Error:

PHP Fatal error:  Can't use function return value in write context in /var/www/html/glpi/test/plugins/purgelogs/inc/purge.class.php on line 277

I'm using PHP 5.4.45.

Thanks for your help.

**Comment by trasher** [comment]
Indeed, the plugin requires PHP 5.5 actually, while it should be 5.4 compatible.

**Comment by narutobaka** [comment]
Hi 

So is purgelog php 5.4 compatible?

get the problem to.

with a php 5.4

cordialy

**Comment by wawax** [comment]
Hello,

Yes it should be compatible with php 5.4

**Comment by narutobaka** [comment]
Hi 

It seems it isn't.

I get this message trying to install the plugin : 

Fatal error: Can't use function return value in write context in /var/www/html/glpi/plugins/purgelogs/inc/purge.class.php on line 277

PurgeLog link i use to download :
http://plugins.glpi-project.org/#/plugin/purgelogs
=> glpi-purgelogs-0.85-1.2.tar.gz

My GLPI  :
 centos-release-7-2  | GLPI  0.90.3 | fusioninventory-for-glpi_0.90.1.3.tar.gz | fusioninventory-agent_windows-x86_2.3.17

My PHP on CentOs : 
php-5.4.16-36.3.el7_2.x86_64

cordialy

**Comment by trasher** [comment]
It's been fixed in 40ab9ebbf9451e35d8ea3fca4e4d8e1ec1795c46; will be available in the next release.
